### ISSUE TITLE
Installation of this module is broken

### ISSUE THREAD

**Issue by miticdjd** [example42/puppet-zip#2]
## Expected Behavior 
Module installs without error.

## Actual Behavior
Module is failing to install, throwing: 

> Error:  Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Cannot use empty string as a class name (file: /etc/puppetlabs/code/environments/production/modules/zip/manifests/init.pp, line: 83, column: 5)

**Comment by alvagante** [comment]
Merged pr, ty
